### ISSUE TITLE
Fred_Api

### ISSUE THREAD

**Issue by Maffemedina** [JvpCode7/algoTrading#1]
Discúlpame no entiendo como guardas el archivo Fred_Api, es decir hay va en formato txt mi ApiKey? Y este Fred_Api está guardado en una carpeta config? No entendí muy bien :) gracias por tu ayuda

**Comment by JvpCode7** [comment]
En la misma carpeta crea un archivo config.py
En este archivo creas la variable  FRED_API con el valor de tu API Key de FRED.

Voy a subir un ejemplo al repositorio. 

Quedo atento a cualquier duda.

**Comment by Maffemedina** [comment]
Muchas gracias , quedo muy claro. excelente tutorial.
